### ISSUE TITLE
text_misc.yml problem

### ISSUE THREAD

**Issue by MAGNAT2645** [mrtenda/CoilSnake#198] opened 2019-08-20 11:44 UTC
text_misc.yml doesn't process "Copy to where?" key.
I have this:
` Copy to where?: "[7C][A5][95][91]?" # Куда?`

But it stays "Copy to where?" in game.
(Custom font)
![изображение](https://user-images.githubusercontent.com/11666918/63344388-c5dba780-c369-11e9-8e75-be7386df11a2.png)

**Comment by ShadowOne333** [comment] 2019-08-20 14:26
Are you sure you tested the right ROM?
You can take a look at my text_misc.yml file from my Spanish translation for reference:
https://github.com/ShadowOne333/EarthBound-Spanish-Translation/blob/master/text_misc.yml

> Copy to where?: "[B8]A d[C3]nde?"

As long as you put everything inside quotes and use square-brackets for the Hex values, it should work. You could also try compiling without the commented part.

**Comment by MAGNAT2645** [comment] 2019-08-20 14:48
I can say with certainty that i've tested right ROM because all things works expect this key.

**Comment by MAGNAT2645** [comment] 2019-08-20 14:54
Also, is there any way to override width of these purple blocks?

**Comment by ShadowOne333** [comment] 2019-08-20 14:57
For the purple blocks, I never found a way to change their width, but I know there should be a way to change them by Hex editing / ASM hacking a couple of addresses and that should be it, I just never did it because I never saw myself in need of it :P

As for the actual problem at hand, can you post both your Font 0.png and your full text_misc.yml, please?

**Comment by MAGNAT2645** [comment] 2019-08-20 15:00
[text_misc.zip](https://github.com/mrtenda/CoilSnake/files/3521280/text_misc.zip)

**Comment by MAGNAT2645** [comment] 2019-08-20 15:07
Can this be due to my ROM is headerless?

**Comment by ShadowOne333** [comment] 2019-08-20 15:12
I can see the problem now.
Actually, a lot of them.

Take a look at line 98 for example:

>   Confirm Food: '[7D][C5][92][9A][9E][91][C6] [96][95][91]:' # Любимая еда:

Notice anything weird in it?
I can see two problems here right away.

1) That line doesn't have the correct format for a YML file
2) You are not using the double quote symbols, you are using ' instead of "

The last one is the most important problem. Everything that uses a custom character NEEDS to be inside double quotes. "[B0 B1 B2]" etc. If you use only ', there will be a problem when compiling, the game won't recognize the character properly and will instead print something else.

Be sure to fix all of those problems in the YML file and then compile again with all of those problems solved.
Line 98 is not the only one with the issue, I can see at least 29 instances where the same thing happens. 

I recommend you use a software like Gedit or Notepad++ for editing the file, because having the text/code being color coded really helps you out to notice errors like this.

**Comment by MAGNAT2645** [comment] 2019-08-20 15:14
I use NotePad++ for any text-based files.
Anyway, thanks for your help. I will test these changes.

**Comment by MAGNAT2645** [comment] 2019-08-20 15:24
It didn't help
![изображение](https://user-images.githubusercontent.com/11666918/63360815-7bb5ee80-c388-11e9-9a44-f16b2f9789e1.png)

**Comment by MAGNAT2645** [comment] 2019-08-20 15:34
Now i have this text_misc content:
```
Ailments:
  Ailment 01: "[72][96][99] [A3][A0][99][9F][91][9F][9A][C6]" # Без сознания
  Ailment 02: "[7C][A2][9A][A3][A4][91][9D][9D][9A][99][91][A8][9A][C6]" # Кристаллизация
  Ailment 03: "[81][91][A2][91][9D][9A][A9]" # Паралич
  Ailment 04: "[84][A0][AA][9F][A0][A4][91]" # Тошнота
  Ailment 05: "[80][A4][A2][91][93][9D][96][9F][9A][96]" # Отравление
  Ailment 06: "[83][A0][9D][9F]. [A5][95][91][A2]" # Солн. удар
  Ailment 07: "[83][A0][A1][96][9F][9A][96]" # Сопение
  Ailment 08: "[74][A2][9A][92]" # Гриб
  Ailment 09: "[80][95][96][A2][98][9A][9E][A0][A3][A4][C3]" # Одержимость
  Ailment 10: "[84][A0][A3][9C][91] [A1][A0] [95][A0][9E][A5]" # Тоска по дому
Battle Menu:
  Auto Fight: "[71][93][A4][A0]" # Авто
  Bash: "[BC][72][9A][A4][C3]" # [BC]Бить
  Defend: "[B8][79][91][C0][9A][A4][91]" # [B8]Защита
  Do Nothing: "[CF][81][A2][A0][A1][A5][A3][A4][9A][A4][C3]" # [CF]Пропустить
  Goods: "[B9][73][96][C0][9A]" # [B9]Вещи
  Mirror: "[BD][79][96][A2][9C][91][9D][A0]" # [BD]Зеркало
  PSI: "[BA][81][83][7A]" # [BA]ПСИ
  Pray: "[BE][7E][A0][9D][9A][A4][93][91]" # [BE]Молитва
  Run Away: "[BB][83][92][96][98][91][A4][C3]" # [BB]Сбежать
  Shoot: "[BA][83][A4][A2][96][9D][C6][A4][C3]" # [BA]Стрелять
  Spy: "[B7][7A][99][A5][A9][9A][A4][C3]" # [B7]Изучить
Equip Menu:
  Arms: "     [82][A5][9C][9A]" # Руки
  Arms Window Title: "[82][A5][9C][9A]" # Руки
  Body: "      [84][96][9D][A0]" # Тело
  Body Window Title: "[84][96][9D][A0]" # Тело
  Defense: "[79][91][C0][9A][A4][91]:" # Защита
  No Equip: '(....)'
  Offense: "[71][A4][91][9C][91]:" # Атака
  Other: "     [81][A2][A0][A9]." # Проч.
  Other Window Title: "[81][A2][A0][A9][96][96]" # Прочее
  To: "[75][A0]:" # До
  Unequip: "...."
  Weapon: "  [80][A2][A5][98][9A][96]" # Оружие
  Weapon Window Title: "[80][A2][A5][98][9A][C6]" # Оружия
Item Menu:
  Drop: "[72][A2][A0][A3]." # Брос.
  Give: "[75][91][A4][C3]" # Дать
  Help: "[81][A0][9E][C0]." # Помщ.
  Use: "[7A][A3][A1]." # Исп.
Menu Action Targets:
  Where: "[7C][A5][95][91]?" # Куда?
  Where 2: "[74][95][96]?" # Где?
  Which: "[89][A4][A0]?" # Что?
  Who: "[7C][A4][A0]?" # Кто?
  Whom: "[7C][A0][9E][A5]?" # Кому?
Other:
  #Lumine Hall Text: "Я ....  Мне пришлось преодолеть многое, чтобы сюда попасть...  Скоро, я буду...
  #  Скоро, я буду...  Что же случится с нами?  Ч...что происходит?  Мои
  #  мысли отображаются на стене...  или...?"
  Lumine Hall Text: "[B6] ....  [7E][9F][96] [A1][A2][9A][AA][9D][A0][A3][C3] [A1][A2][96][A0][95][A0][9D][96][A4][C3] [9E][9F][A0][94][A0][96], [A9][A4][A0][92][C2] [A3][C5][95][91] [A1][A0][A1][91][A3][A4][C3]...  [83][9C][A0][A2][A0], [C6] [92][A5][95][A5]...
    [83][9C][A0][A2][A0], [C6] [92][A5][95][A5]...  [89][A4][A0] [98][96] [A3][9D][A5][A9][9A][A4][A3][C6] [A3] [9F][91][9E][9A]?  [89]...[A9][A4][A0] [A1][A2][A0][9A][A3][A7][A0][95][9A][A4]?  [7E][A0][9A]
    [9E][C2][A3][9D][9A] [A0][A4][A0][92][A2][91][98][91][C5][A4][A3][C6] [9F][91] [A3][A4][96][9F][96]...  [9A][9D][9A]...?"
  Player Name Prompt: "[81][A0][98][91][9D][A5][9B][A3][A4][91], [93][91][AA][96] [9A][9E][C6]." # Пожалуйста, ваше имя.
Out of Battle Menu:
  Check: "[81][A2][A0][93][96][A2][9C][91]" # Проверка
  Equip: "[B4][9C][9A][A1][9A][A2]." # Экипир.
  Goods: "[73][96][C0][9A]" # Вещи
  PSI: "[81][83][7A]" # ПСИ
  Status: "[83][A4][91][A4][A5][A3]" # Статус
  Talk to: "[74][A0][93][A0][A2][9A][A4][C3]" # Говорить
PSI Menu:
  PP Cost: "[88][96][9F][91] [80][81]" # Цена ОП
  Row Back: "[79][91][95][9F][9A][9B] [A2][C6][95]" # Задний ряд
  Row Front: "[81][96][A2][96][95][9F][9A][9B] [A2][C6][95]" # Передний ряд
  Row To: '' # Лишнее, можно оставить пустым
  To all enemies: "[73][A3][96][A7] [93][A2][91][94][A0][93]" # Всех врагов
  To all of us: "[73][A3][96][A7] [9F][91][A3]" # Всех нас
  To all of us 2: "[73][A3][96][A7] [9F][91][A3]" # Всех нас
  To enemy: "[73][A2][91][94][91]" # Врага
  To one enemy: "[80][95][9F][A0][94][A0] [93][A2][91][94][91]" # Одного врага
  To one enemy 2: "[80][95][9F][A0][94][A0] [73][A2][91][94][91]" # Одного Врага
  To one of us: "[80][95][9F][A0][94][A0] [9A][99] [9F][91][A3]" # Одного из нас
  To one of us 2: "[80][95][9F][A0][94][A0] [75][A2][A5][94][91]" # Одного Друга
  To row of foes: "[82][C6][95] [93][A2][91][94][A0][93]" # Ряд врагов
  himself: "[A3][96][92][C6]" # себя
PSI Types:
  Assist: "[73][A3][A1][A0][9E]." # Вспом.
  Offense: "[71][A4][91][9C][91]" # Атака
  Other: "[81][A2][A0][A9][96][96]" # Прочее
  Recover: "[7D][96][A9][96][9F][9A][96]" # Лечение
Starting Text:
  Ask Name 1: "[81][A0][98][91][9D][A5][9B][A3][A4][91], [9F][91][99][A0][93][9A][A4][96] [96][94][A0]." # Пожалуйста, назовите его.
  Ask Name 2: "[76][97] [A4][A0][98][96]." # Её тоже.
  Ask Name 3: "[7F][91][99][A0][93][9A][A4][96] [A3][93][A0][96][94][A0] [95][A2][A5][94][91]." # Назовите своего друга.
  Ask Name 4: "[7F][91][99][A0][93][9A][A4][96] [95][A2][A5][94][A0][94][A0] [95][A2][A5][94][91]." # Назовите другого друга.
  Ask Name Food: "[7D][C5][92][9A][9E][91][C6] [96][95][91]?" # Любимая еда?
  Ask Name PSI: "[83][91][9E][91][C6] [9D][C5][92][9A][9E][91][C6] [93][96][C0][C3]?" # Самая любимая вещь?
  Ask Name Pet: "[7F][91][99][A0][93][9A][A4][96] [A3][93][A0][96][94][A0] [A1][9A][A4][A0][9E][A8][91]." # Назовите своего питомца.
  Confirm All: "[73][C2] [A5][93][96][A2][96][9F][C2]?" # Вы уверены?
  Confirm All No: "[7F][96]-[91]" # Не-а
  Confirm All Yes: "[71][94][91]" # Ага
  Confirm Delete: "[73][C2] [A1][A2][91][93][95][91] [A7][A0][A4][9A][A4][96] [A3][A4][96][A2][96][A4][C3]?" # Вы правда хотите стереть?
  Confirm Delete No: "[7F][96][A4]" # Нет
  Confirm Delete Yes: "[75][91]" # Да
  Confirm Food: "[7D][C5][92][9A][9E][91][C6] [96][95][91]:" # Любимая еда:
  Confirm PSI: "[7D][A5][A9][AA][91][C6] [93][96][C0][C3]:" # Лучшая вещь:
  Continue: "[7A][94][A2][91][A4][C3]" # Играть
  Copy: "[7C][A0][A1][9A][A2][A0][93][91][A4][C3]" # Копировать
  Copy to where?: "[7C][A5][95][91]?" # Куда?
  Delete: "[85][95][91][9D][9A][A4][C3]" # Удалить
  Select Sound: "[73][C2][92][96][A2][9A][A4][96] [A5][A3][A4][91][9F][A0][93][9C][A5] [99][93][A5][9C][91]." # Выберите установку звука.
  Select Sound Mono: "[7E][A0][9F][A0]" # Моно
  Select Sound Stereo: "[83][A4][96][A2][96][A0]" # Стерео
  Select Speed: "[83][9C][A0][A2][A0][A3][A4][C3] [A4][96][9C][A3][A4][91]?" # Скорость текста?
  Select Style: "[7C][91][9C][A0][9B] [A3][A4][9A][9D][C3] [A0][9C][A0][9F] [93][91][9E]    [A1][A0] [95][A5][AA][96]?" # Какой стиль окон вам    по душе?
  Set Up: "[7F][91][A3][A4][A2][A0][9A][A4][C3]" # Настроить
  Start New Game: "[7F][91][A9][91][A4][C3] [7A][94][A2][A5]" # Начать Игру
  Text Speed: "[83][9C][A2].[84][96][9C][A3][A4][91]:" # Скр.Текста:
  Text Speed Fast: "[72][C2][A3][A4][A2][A0]" # Быстро
  Text Speed Medium: "[83][A2][96][95][9F][96]" # Средне
  Text Speed Slow: "[7E][96][95][9D]." # Медл.
Status Window:
  Defense: "[79][91][C0][9A][A4][91]:" # Защита:
  Exp. for next level: "[80][A1][C2][A4] [95][A0] [A3][9D][96][95]. [A5][A2]." # Опыт до след. ур.
  Experience Points: "[80][A9][9C][9A] [80][A1][C2][A4][91]:" # Очки Опыта:
  Guts: "[7E][A5][98].:" # Муж.:
  Hit Points: "[79][95][A0][A2][A0][93][C3][96]:" # Здоровье:
  IQ: "[7A][84]:" # ИТ:
  Level: "[85][A2][A0][93].:" # Уров.:
  Luck: "[85][95][A9].:" # Удача:
  Offense: "[71][A4][91][9C][91]:" # Атака:
  PSI Prompt: "@[7F][91][98][9E][9A][A4][96] -[71]- [95][9D][C6] [9A][9F][A6]. [A0] [81][83][7A]." # Нажмите -А- для инф. о ПСИ.
  Psychic Points: "[80][A9][9C][9A] [81][83][7A]:" # Очки ПСИ:
  Speed: "[83][9C][A0][A2].:" # Скор.:
  Vitality: "[78][9A][93][A5][A9].:" # Живуч.:
Window Titles:
  Escargo Express Window Title: "[87][A2][91][9F]. [73][96][C0][9A]" # Хран. Вещи
  Phone Window Title: "[79][93][9F].:" # Звн.:

```

**Comment by ShadowOne333** [comment] 2019-08-20 15:36
The ' symbols were not the only issue.
Delete the : symbols from each and every comment (after #) as well.

**Comment by MAGNAT2645** [comment] 2019-08-20 15:38
Ah, okay.

**Comment by MAGNAT2645** [comment] 2019-08-20 15:44
Didn't help

**Comment by ShadowOne333** [comment] 2019-08-20 15:50
Isn't Куда supposed to be [7C][A5][75][91]?
The [95] is "g"

**Comment by MAGNAT2645** [comment] 2019-08-20 15:55
I have Python Script to convert these characters and "Куда" is "[7C][A5][95][91]"

**Comment by MAGNAT2645** [comment] 2019-08-20 15:57
g is 'д'

**Comment by MAGNAT2645** [comment] 2019-08-20 16:05
Removed comments, didn't help

**Comment by ShadowOne333** [comment] 2019-08-20 16:06
Can you post your project as a zip to try on my end, please?
You can remove it once I download it if you want.

**Comment by MAGNAT2645** [comment] 2019-08-20 16:07
https://github.com/MAGNAT2645/Earthbound-RUS

It has some outdated files (at least text_misc.yml), i can post them here.

**Comment by MAGNAT2645** [comment] 2019-08-20 16:09
Oh, also there's some missing files because i will upload them after translation release.
So, should i post ZIP with full project?

**Comment by ShadowOne333** [comment] 2019-08-20 17:19
Found the issue.

The "Copy to where?" text is referenced in two places in the ROM.
CoilSnake only takes into account one of them, not the second.
The same thing happens with other options, like "Copy", "Delete", "Set Up" and "Config" I believe.

I did a special script for the Spanish translation years ago which takes the remaining instances into account, and you can easily adapt it to your translation as well.

Here's my script:
https://github.com/ShadowOne333/EarthBound-Spanish-Translation/blob/master/ccscript/asm_file_select.ccs

Let me know if the issue is fixed with this new script once you made your changes into it.

**Comment by MAGNAT2645** [comment] 2019-08-20 17:33
Yeah, it's works now.
![изображение](https://user-images.githubusercontent.com/11666918/63369741-094e0a00-c39a-11e9-8121-827fdc20ab5e.png)

So, i think CoilSnake should include 0xC1F208.

Also, i have 2 small questions.
1: Is there any way to find addresses to Raw text from Cast (only for Paula, Poo and Ness texts)? I want to add "Prince" before Poo name
2: I saw somewhere title command that can add window titles. Have you seen it anywhere?

**Comment by ShadowOne333** [comment] 2019-08-20 18:10
Nice, you can close the issue now.

As for your questions:
1. I haven't tried looking into those, but I think the raw RAM names are maybe taken from somewhere around C4E80C and C4E87A.
I'm not sure what the game might do if I NOP the JSLs in those addresses.
2. Yeah, you need EB++ for those to work.
But you can only add window titles for actual text, like
> title_ness(1)    <---This will open up the window #1 with the title window set to the name of Ness
> title_paula(1)   <---Same as above
> title_jeff(1)
> title_poo(1)
> title_king(1)

To input your own window title, you have to use:
> title(1, "Name Here")
I think that's how it's used in EB++, but afaik you cannot use it for other windows like status, equipment, etc, since those already have their own code for window titles in place.

**Comment by MAGNAT2645** [comment] 2019-08-20 18:14
So, title_* commands already built-in to EB++? I want it for dialogues.
Anyway, thanks for your help. You're great PK Hacker :smile:

**Comment by ShadowOne333** [comment] 2019-08-20 18:15
Correct, the title commands are already in EB++.
You can use them for dialogues just fine. :)
And thanks! :smile:

**Comment by MAGNAT2645** [comment] 2019-08-20 18:18
Is [this version](https://github.com/MAGNAT2645/Earthbound-RUS/blob/master/ccscript/EBPP_Disassembly_HardwareCompatible_v1_1.ccs) enough for these commands?

**Comment by ShadowOne333** [comment] 2019-08-20 18:21
Correct.
You can find the whole list of commands for EB++ in here:
https://github.com/mrtenda/mobile-sprout/blob/master/lib/ebpp_std.ccs

**Comment by PhoenixBound** [comment] 2019-08-20 18:22
Since this issue is about a bug in CoilSnake, it would be a good idea to reopen the issue. CoilSnake should handle both instances of the text, even though it doesn't right now.

**Comment by MAGNAT2645** [comment] 2019-08-20 18:23
Oh, okay. If necessary...

**Closed** 2019-08-20 23:29 UTC

**Comment by MAGNAT2645** [comment] 2019-08-29 15:14
Sorry for disturbing this closed issue, but since i asked the question about **title** command here, i want to know how to disable/turn off titles without closing windows. Is this possible?
I've applied "Гийгас" ("Giygas" in english) title to Giygas's replics.
![изображение](https://user-images.githubusercontent.com/11666918/63952609-4fd9ed80-ca99-11e9-9234-b02c03c782cc.png)

But title stays until window 14 closed.
![изображение](https://user-images.githubusercontent.com/11666918/63952739-87489a00-ca99-11e9-91f5-94848fc545af.png)
("Ness took 9 HP of damage" on english)

**Comment by ShadowOne333** [comment] 2019-08-29 15:20
Sadly, it's not possible to remove the titles without closing the window itself.
What you can do, is close and reopen the window in the same text-line.

For example, this is something I did for the text for Ness in Magicant after defeating the Nightmare:
`call(l_0xc77c50) title_ness(1) "@...That's me!" next "{window_closetop}{window_open(1)}"`

So basically I made it so that when Ness says "That's me!", his name appears on the window for a brief moment. After that text is done, the top window will close, and the window 1 will reopen at the exact moment, so you can't even tell the window got closed at all.

You could do something similar for Giygas' text.
Maybe do it so that after his text, you make the button prompt and then window_closetop -> window_open(14). That could work.

Let me know how the test went!

**Comment by MAGNAT2645** [comment] 2019-08-29 15:25
But what if i have **eob**?
![изображение](https://user-images.githubusercontent.com/11666918/63953560-012d5300-ca9b-11e9-9cd5-479b0f0f2b5f.png)

Will **window_open**(14) work after **eob** or **end**?

**Comment by ShadowOne333** [comment] 2019-08-29 15:25
Use them after.
Take my line for reference.
I closed the window and opened it after the `next` command.
Try doing it before the `eob`

**Comment by MAGNAT2645** [comment] 2019-08-29 15:37
So i did this
![изображение](https://user-images.githubusercontent.com/11666918/63954453-8e24dc00-ca9c-11e9-9e3e-22b72f80b1dd.png)

It works, but Giygas says same dialogue repeatly
![изображение](https://user-images.githubusercontent.com/11666918/63954593-c75d4c00-ca9c-11e9-9b85-10ce2c3167f9.png)
("Ness")

**Comment by ShadowOne333** [comment] 2019-08-29 15:38
Oh sorry, I meant after the `eob` :P

**Comment by MAGNAT2645** [comment] 2019-08-29 16:20
Uh, i did this
![изображение](https://user-images.githubusercontent.com/11666918/63957893-b9aac500-caa2-11e9-8904-998a189897f9.png)

Now title stays, but dialogue still repeats (like random number doesn't work at all, i think)

**Comment by ShadowOne333** [comment] 2019-08-29 17:32
Put the window close and open commands in between the [1F 04 01] and the [03].
Also, if I recall correctly, during the first part of the battle Giygas only says "...Ness..." over and over, until you reach the part where Porky comes back, then he starts randomizing his speech pattern.

Test all of the battle as a whole when you enable these changes.
Also, try to add the title for Paula and her prayers as well, in a similar pattern (after the `sound` command and before the `eob`).

**Comment by MAGNAT2645** [comment] 2019-08-29 18:29
For Paula i did like this:
![изображение](https://user-images.githubusercontent.com/11666918/63964560-ccc49180-cab0-11e9-8310-502042604e15.png)
("Paula prayed from the bottom of her heart" and then **title** and her line)

So, yeah, it works. Thanks!

I have last question about storing registers.
I want to put gender check for texts like "Ness gave the Cookie to Paula".
Is there any proper way to return gender for [1C 02 00] and [1C 02 FF] ?
`"[19 19 00 00]{swap}@[1C 02 00] gave the {swap}[1C 05 00]" linebreak`


There's also problem with this text:
![изображение](https://user-images.githubusercontent.com/11666918/63966354-82451400-cab4-11e9-95ca-424a0a4435e0.png)
I can properly get {user} gender but {targer_gender} returns wrong gender in this case.
Maybe i should store register anywhere else?

**Comment by ShadowOne333** [comment] 2019-08-29 19:02
So how did you end up making Giygas' lines? Could you please post an example?
For Paula I believe the window closes itself by default, to allow for the Window 1 to be opened up for the prayer sequences.

As for the gender question. where exactly did you get the `targer_gender` and `user_gender` commands?
I can't find them anywhere.

**Comment by MAGNAT2645** [comment] 2019-08-29 19:11
Here's example of Giygas line:
```
l_0xc9ee68:
//	title(14, "Гийгас")
	newline
	title(14, "[74][9A][9B][94][91][A3]")
	"[1F 04 02]@<.....[1C 01 08]{pause(1)}...>[1F 04 01][03]{window_close(14)}{window_open(14)}" eob
```

About Paula, window 14 closes itself after screen fading.

About these commands, i defined them so I wouldn't forget the codes.
```
command user_gender		"[1C 14 01]"
command user_number		"[1C 14 02]"
command target_gender		"[1C 15 01]"
command target_number		"[1C 15 02]"
command char_slot(num)		"[19 10 {byte num}]"
```
They work like a charm, but in some cases i can't get proper gender (maybe due to register changes?)

**Comment by ShadowOne333** [comment] 2019-08-29 19:19
The commands look okay.
Just be careful about those store/load registers and the swaps. Try to read the ccscript documentation related to those ones, and perhaps you might notice why it could be failing for the target one.

**Comment by MAGNAT2645** [comment] 2019-08-29 19:23
I've read CCScript reference many times, but i can't understand why {target_gender} returns wrong gender (AND it seems that gender returns from item 1C 05 00 somehow instead of {target})

**Comment by ShadowOne333** [comment] 2019-08-29 19:38
I'm not too sure about those.
I have not played around that much with those control codes to know exactly what might be wrong, but if I may, I think it might have to with either the `swap`, `store registers` or `load registers`, or the positioning of these in the lines.
Try to copy-paste the one from user and replacing just one with the other, and if that doesn't work, try experimenting with the mentioned commands.

**Comment by MAGNAT2645** [comment] 2019-08-29 21:32
I think it's not possible to get {target} gender in this case, because [19 1F] returns battle action argument (which contains both {user} and {target} i think), then swaps it to get item argument. So item argument doesn't seem to override result, because result and argument - different things as i know.

**Comment by MAGNAT2645** [comment] 2019-08-29 21:43
So i did some more testing and i think, this works properly in battle, but outside i can't get {target} gender properly.

**Comment by MAGNAT2645** [comment] 2019-08-29 22:32
At least, i've fixed one of my problems.
> I have last question about storing registers.
> I want to put gender check for texts like "Ness gave the Cookie to Paula".
> Is there any proper way to return gender for [1C 02 00] and [1C 02 FF] ?
> "[19 19 00 00]{swap}@[1C 02 00] gave the {swap}[1C 05 00]" linebreak " to [1C 02 FF]." end

So i did this:
```
l_0xc7e4a4:
	/*
	"[19 19 00 00]{swap}@[1C 02 00] передал{swap}{call(data_gender.l_gendersuffix)} {swap}{rtoarg}[1C 05 00]" linebreak
	"  персонажу [1C 02 FF]." end
	*/
	"[19 19 00 00]{swap}@[1C 02 00] [A1][96][A2][96][95][91][9D]{swap}{call(data_gender.l_gendersuffix)} {swap}{rtoarg}[1C 05 00]" linebreak
	"  [A1][96][A2][A3][A0][9F][91][98][A5] [1C 02 FF]." end
```

Now it works like i wanted.
